spring:
  application:
    name: statistic-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/statistic
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
server:
  port: 8089
